language: php
php:
  - '7.2'
git:
  quiet: true
notifications:
  email:
    on_success: never
before_script:
    - yes "\n" | pecl install "channel://pecl.php.net/mosquitto-0.4.0"
    - echo "extension=mosquitto.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - composer install
script:
  # Search for PHP syntax errors.
  - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  # Run PHPCS.
  - vendor/bin/phpcs . ./phpcs.xml
  ## PHP Mess Detector
  - vendor/bin/phpmd ./src,./tests text ./phpmd.xml
  ## PHPUnit Tests
  - vendor/bin/phpunit --coverage-xml ./phpunit.xml
  